### ISSUE TITLE
PrettyError reneder adds extra \n

### ISSUE THREAD

**Issue by reggi** [AriaMinaei/pretty-error#27]
Is there a way to prevent the render from adding a `\n`?

**Comment by AriaMinaei** [comment]
This is probably because of a bottom margin on the last trace line. Fixing it would require adding pseudo-selectors to the style engine. But I think that would be an overkill since this is imho a trivial issue.

But I could be wrong, so, let me know if you think this issue is more important than I think.

**Comment by reggi** [comment]
Nope, thanks.
